[package]
name = "hell"
description = "The Holy shELL"
license = "AGPL-3.0"
version = "0.1.0"
authors = ["inkyu <gofiri@gmail.com>"]
edition = "2018"

[dependencies]
dope = {version = "0", git = "https://github.com/inq/dope"}
